dist: bionic
sudo: required

language: generic

addons:
  sonarcloud:
    organization: "nicolaspernoud-github"
    token: $SONAR_TOKEN
  jdk:
    - oraclejdk8
cache:
  directories:
    - "$HOME/.sonar/cache"

before_install:
  # Install Docker 18.09+ for enabling DOCKER_BUILDKIT
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo cat /etc/docker/daemon.json
  # Apr 22, 2019: daemon.json contains `{"registry-mirrors": ["https://mirror.gcr.io"]}`, doesn't work well with BuildKit?
  - sudo rm -f /etc/docker/daemon.json
  - sudo systemctl restart docker

services:
  - docker

script:
  # sonarcloud scan
  - npm install typescript
  - sonar-scanner
  # create container and push it to docker hub
  - set -e
  - export REPO=nicolaspernoud/ninicobox-v3
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - echo $REPO:$TAG:$TRAVIS_BUILD_NUMBER
  - export DOCKER_BUILDKIT=1
  - docker build -t $REPO:$TRAVIS_BUILD_NUMBER .
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $REPO:$TAG
  - docker push $REPO
