
dist: trusty
sudo: required

language: generic

addons:
  sonarcloud:
    organization: "nicolaspernoud-github"
    token: $SONAR_TOKEN
  jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.sonar/cache'

services:
  - docker

script:
  # sonarcloud scan
  - npm install typescript
  - sonar-scanner
  # create container and push it to docker hub
  - set -e
  - export REPO=nicolaspernoud/ninicobox-v3
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - echo $REPO:$TAG:$TRAVIS_BUILD_NUMBER
  - docker build -t $REPO:$TRAVIS_BUILD_NUMBER .
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $REPO:$TAG
  - docker push $REPO