version: "2.4"

services:

  docker-ninicobox-container:
    image: nicolaspernoud/ninicobox-v3
    build: .
    restart: unless-stopped
    mem_limit: 512m
    user: '1000'
    command: -https_port=2443 -debug -hostname=box.127.0.0.1.nip.io
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 443:2443
      - 80:80